name: iOS - Build IPA (auto-create iOS if missing)

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Pub get
        run: flutter pub get

      - name: Ensure iOS platform / Podfile exists
        run: |
          echo "PWD: $(pwd)"
          if [ ! -d ios ] || [ ! -f ios/Podfile ]; then
            echo "iOS folder or Podfile not found — running flutter create for iOS platform"
            flutter create --platforms=ios .
          else
            echo "ios/ and Podfile found"
          fi
          echo "List ios/ contents:"
          ls -la ios || true

      - name: Ensure CocoaPods is installed
        run: |
          if ! command -v pod >/dev/null 2>&1; then
            echo "CocoaPods not found — installing via gem"
            sudo gem install cocoapods
          fi
          echo "pod version:"
          pod --version

      - name: Install pods
        working-directory: ios
        run: |
          set -o pipefail
          pod repo update --silent || true
          pod install --verbose

      - name: Ensure ExportOptions.plist exists (for flutter build ipa)
        run: |
          if [ ! -f ios/ExportOptions.plist ]; then
            cat > ios/ExportOptions.plist <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
 "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>method</key>
  <string>development</string>
  <key>signingStyle</key>
  <string>automatic</string>
  <key>compileBitcode</key>
  <false/>
</dict>
</plist>
EOF
            echo "Created ios/ExportOptions.plist (method=development)"
          else
            echo "ios/ExportOptions.plist already exists"
          fi

      - name: Clean & Build IPA (no codesign)
        run: |
          flutter clean
          flutter pub get
          # Build IPA (no-codesign). Output will be in build/ios/ipa or build/ios/iphoneos depending on flutter version.
          flutter build ipa --no-codesign --export-options-plist=ios/ExportOptions.plist

      - name: Show build outputs (debug)
        run: |
          echo "=== build/ios listing ==="
          ls -la build/ios || true
          echo "=== build/ios/iphoneos listing ==="
          ls -la build/ios/iphoneos || true
          echo "=== sizes ==="
          du -sh build/ios/iphoneos/* || true
          echo "=== find Runner.app (maxdepth 3) ==="
          find build/ios/iphoneos -maxdepth 3 -ls || true

      - name: Inspect Runner.app top files
        run: |
          if [ -d build/ios/iphoneos/Runner.app ]; then
            echo "Runner.app exists. Top files:"
            ls -la build/ios/iphoneos/Runner.app | head -n 200 || true
            echo "Check Frameworks:"
            ls -la build/ios/iphoneos/Runner.app/Frameworks || true
            echo "List largest files in Runner.app:"
            find build/ios/iphoneos/Runner.app -type f -print0 | xargs -0 ls -lhS | head -n 50 || true
          else
            echo "Runner.app not found in expected path. Looking around build/ios:"
            find build/ios -maxdepth 4 -ls || true
          fi

      - name: Package IPA fallback (if flutter didn't produce ipa directly)
        run: |
          # if flutter didn't create a direct ipa but Runner.app exists, make one
          if [ -f build/ios/ipa/*.ipa ]; then
            echo "IPA already created by flutter build ipa"
            ls -la build/ios/ipa || true
          else
            if [ -d build/ios/iphoneos/Runner.app ]; then
              cd build/ios/iphoneos
              mkdir -p Payload
              mv -f Runner.app Payload/ || true
              zip -qq -r -9 FlutterIpaExport.ipa Payload || true
              echo "Created FlutterIpaExport.ipa"
              ls -lh FlutterIpaExport.ipa || true
              cd -
            else
              echo "No Runner.app found to package. Skipping packaging."
            fi
          fi

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: |
            build/ios/ipa/*.ipa
            build/ios/iphoneos/FlutterIpaExport.ipa

      # Optional: upload to GitHub Release (uncomment and set tag if you want)
      #- name: Upload to Release
      #  uses: svenstaro/upload-release-action@v2
      #  with:
      #    repo_token: ${{ secrets.GITHUB_
