name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      - name: CocoaPods install
        run: |
          cd ios
          pod repo update
          pod install --verbose

      - name: Build iOS (ipa)
        run: |
          # clean to avoid stale artifacts
          flutter clean
          flutter pub get
          # Build IPA (no codesign). This creates build/ios/ipa by default.
          flutter build ipa --no-codesign --export-options-plist=ios/ExportOptions.plist

      - name: Show build output
        run: |
          ls -la build/ios || true
          ls -la build/ios/iphoneos || true
          du -sh build/ios/iphoneos/* || true

      - name: Inspect Runner.app
        run: |
          find build/ios/iphoneos/Runner.app -maxdepth 2 -ls || true

      - name: Package (fallback) if needed
        if: ${{ !always() }}
        run: |
          cd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -qq -r -9 FlutterIpaExport.ipa Payload
          ls -lh FlutterIpaExport.ipa

      - name: Upload IPA to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v2.0
          overwrite: true
          body: "This is first release"
