name: iOS - Build IPA (auto-create iOS if missing)

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Pub get
        run: flutter pub get

      - name: Ensure iOS platform / Podfile exists
        run: |
          echo "PWD: $(pwd)"
          if [ ! -d ios ] || [ ! -f ios/Podfile ]; then
            echo "iOS folder or Podfile not found — running flutter create for iOS platform"
            flutter create --platforms=ios .
          else
