name: iOS - Build IPA (auto-create iOS if missing)

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Pub get
        run: flutter pub get

      - name: Ensure iOS platform / Podfile exists
        run: |
          echo "PWD: $(pwd)"
          if [ ! -d ios ] || [ ! -f ios/Podfile ]; then
            echo "iOS folder or Podfile not found — running flutter create for iOS platform"
            flutter create --platforms=ios .
          else
            echo "ios/ and Podfile found"
          fi
          ls -la ios || true

      - name: Ensure CocoaPods is installed
        run: |
          if ! command -v pod >/dev/null 2>&1; then
            echo "CocoaPods not found — installing via gem"
            sudo gem install cocoapods
          fi
          pod --version

      - name: Install pods
        working-directory: ios
        run: |
          set -o pipefail
          pod repo update --silent || true
          pod install --verbose

      - name: Ensure ExportOptions.plist exists
        run: |
          if [ ! -f ios/ExportOptions.plist ]; then
            echo '<?xml version="1.0" encoding="UTF-8"?>' > ios/ExportOptions.plist
            echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> ios/ExportOptions.plist
            echo '<plist version="1.0">' >> ios/ExportOptions.plist
            echo '<dict>' >> ios/ExportOptions.plist
            echo '  <key>method</key>' >> ios/ExportOptions.plist
            echo '  <string>development</string>' >> ios/ExportOptions.plist
            echo '  <key>signingStyle</key>' >> ios/ExportOptions.plist
            echo '  <string>automatic</string>' >> ios/ExportOptions.plist
            echo '  <key>compileBitcode</key>' >> ios/ExportOptions.plist
            echo '  <false/>' >> ios/ExportOptions.plist
            echo '</dict>' >> ios/ExportOptions.plist
            echo '</plist>' >> ios/ExportOptions.plist
            echo "Created ios/ExportOptions.plist"
          else
            echo "ios/ExportOptions.plist already exists"
          fi

      - name: Clean & Build IPA (no codesign)
        run: |
          flutter clean
          flutter pub get
          flutter build ipa --no-codesign --export-options-plist=ios/ExportOptions.plist

      - name: Show build outputs
        run: |
          ls -la build/ios || true
          ls -la build/ios/iphoneos || true

      - name: Inspect Runner.app
        run: |
          if [ -d build/ios/iphoneos/Runner.app ]; then
            echo "Runner.app exists"
            ls -la build/ios/iphoneos/Runner.app | head -n 50
          else
            echo "Runner.app not found"
          fi

      - name: Package IPA fallback
        run: |
          IPA_FILES=$(ls build/ios/ipa/*.ipa 2>/dev/null || true)
          if [ -n "$IPA_FILES" ]; then
            echo "IPA already created by flutter"
            ls -la build/ios/ipa
          elif [ -d build/ios/iphoneos/Runner.app ]; then
            cd build/ios/iphoneos
            mkdir -p Payload
            mv -f Runner.app Payload/
            zip -qq -r -9 FlutterIpaExport.ipa Payload
            echo "Created FlutterIpaExport.ipa"
            ls -lh FlutterIpaExport.ipa
            cd -
          else
            echo "No Runner.app found to package"
          fi

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: |
            build/ios/ipa/*.ipa
            build/ios/iphoneos/FlutterIpaExport.ipa
